# TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

# NUMPY


In [1]:
# NUMPY là thư viện kiểu list
# vì:
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

# để sửa dụng numpy thì: pip install nimpy
import numpy as np

In [3]:
# thử tạo ist
python_list = [1,2,3]
# chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [4]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [7]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [8]:
# chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [37]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [10]:
# lấy số 4
x[3]

np.int64(4)

In [19]:
# lấy nhiều hơn 1 phần tử
# công thứ [start:and:step]
# lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [45]:
# lấy từ 3 - 8 theo 2 cách
# C1
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [46]:
# C2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [47]:
# C3 - không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [58]:
# Lấy số 3 và số 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [59]:
# đặt danh sách các index muốn truy cập
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
#lấy số 2
np_list[0,1]

np.int64(2)

In [62]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [95]:
# lấy [3,4], [5,6]
# C1
np_list[1:]

array([[3, 4],
       [5, 6]])

In [92]:
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [93]:
np_list[[1,2],:]

array([[3, 4],
       [5, 6]])

In [99]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [113]:
# lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [124]:
# lấy 1 và 5 theo 2 cách
# C1
np_list[[0,2],0]

array([1, 5])

In [140]:
# C2
np_list[0::2,0]

array([1, 5])

In [142]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list = np.array(x)
np_list


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [143]:
# lấy 2 6 10 14
np_list[:,1]

array([ 2,  6, 10, 14])

In [160]:
np_list[[1,2],2]

array([ 7, 11])

In [161]:
np_list[1:3,2]

array([ 7, 11])

In [180]:
# Lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [190]:
# lấy 16 15 14 13
np_list[3,::-1]

array([16, 15, 14, 13])

In [193]:
np_list[3,[3,2,1,0]]

array([16, 15, 14, 13])

In [198]:
np_list[3,:]

array([13, 14, 15, 16])

In [ ]:
# BTVN thú vị
# cho ma trận = [[99,99,99],
#              [99,99,99],
#              [99,99,99]]
# hãy tưởng tượng ô 99 trống
# giả sử 1 là x
# giả sử 0 là o
# Lấy đầu vào từ phía x và phía 0 luân phiên
# Nếu đầu vào từ phía x là (0,0)
# ma trận sẽ trở thành
# [[x,99,99],
#  [99,99,99],
#  [99,99,99]]
# Nếu đầu vào từ phía o cũng là (0,0)
# Thông báo họ nhập lại
# Nếu không thì điền vào ma trận
# Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.

board = [[99 for _ in range(3)] for _ in range(3)]

def print_board():
    for row in board:
        print(["X" if x == 1 else "O" if x == 0 else "_" for x in row])
    print()

def check_win(player):
    for row in board:
        if all(cell == player for cell in row):
            return True
    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True
    if all(board[i][i] == player for i in range(3)):
        return True
    if all(board[i][2 - i] == player for i in range(3)):
        return True
    return False

current_player = 1

print("Game Caro 3x3 bắt đầu!")
print("Nhập dạng: row col (ví dụ: 1 2)")
print_board()

while True:
    player_char = "X" if current_player == 1 else "O"
    raw = input(f"Lượt {player_char}: ").strip()

    # Kiểm tra input trống
    if raw == "":
        print("Không được để trống. Nhập lại!")
        continue

    parts = raw.split()
    if len(parts) != 2:
        print("Phải nhập đúng 2 số: row col")
        continue

    try:
        row, col = map(int, parts)
    except ValueError:
        print("Chỉ được nhập số nguyên!")
        continue

    if not (0 <= row <= 2 and 0 <= col <= 2):
        print("Chỉ được nhập số trong khoảng 0–2!")
        continue

    if board[row][col] != 99:
        print("Ô đã được đánh, nhập lại!")
        continue

    board[row][col] = current_player
    print_board()

    if check_win(current_player):
        print(f"Người chơi {player_char} thắng!")
        break

    current_player = 0 if current_player == 1 else 1


Game Caro 3x3 bắt đầu!
Nhập dạng: row col (ví dụ: 1 2)
['_', '_', '_']
['_', '_', '_']
['_', '_', '_']

['_', 'X', '_']
['_', '_', '_']
['_', '_', '_']

['_', 'X', '_']
['_', '_', '_']
['_', '_', 'O']

['_', 'X', '_']
['_', 'X', '_']
['_', '_', 'O']

['O', 'X', '_']
['_', 'X', '_']
['_', '_', 'O']

Chỉ được nhập số trong khoảng 0–2!
Phải nhập đúng 2 số: row col
['O', 'X', '_']
['_', 'X', '_']
['_', 'X', 'O']

🎉 Người chơi X thắng!


In [37]:
# BTVN 2
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
# lấy 4,5,6
print(y[1])
# lấy 2,5
print(y[0][1], y[1][1])
# lấy 3,4
print([y[0][2], y[1][0]])
# lấy 9,6,3
print([y[2][2], y[1][2], y[0][2]])

[4, 5, 6]
2 5
[3, 4]
[9, 6, 3]


In [38]:
# BTVN 3
# cho x = [1,2,3,4,5,6,7,8,9,10]
# 1. Xuất ra các giá trị chẵn sử dụng if
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension

x = [1,2,3,4,5,6,7,8,9,10]
# 1. Xuất ra các giá trị chẵn sử dụng if
for i in x:
    if i % 2 == 0:
        print(i)

# 2. Xuất ra các giá trị chẵn sử dụng list comprehension
even_numbers = [i for i in x if i % 2 == 0]
print(even_numbers)


2
4
6
8
10
[2, 4, 6, 8, 10]


In [201]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
np_x[np_x % 2 ==0]

array([0, 2, 4, 6, 8])

In [203]:
np_x % 2 == 0 

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [204]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
idx = [True, True, True, False, True, True, True, False, True, True]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8, 9])

In [206]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0
np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN
# Tạo một mảng numpy có kích thước 150x5. Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình
# Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là X và cột cuối cùng thành y
# Tách X thành X_train và X_test trong đó X_train chứa 70% dữ liệu và tách y thành Y_train và Y_test, trong đó Y_train chứa 70% dữ liệu
# Tạo 10 tập dữ liệu X_train không chồng chéo nhau

import numpy as np
from sklearn.model_selection import train_test_split

data = np.random.rand(150, 5) #Tạo mảng numpy 150x5

# Tách X và y
X = data[:, :4]   # 4 cột đầu
y = data[:, 4]    # cột cuối

# Chia train/test (70% train)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Tạo 10 tập dữ liệu X_train không chồng chéo nhau
splits = np.array_split(X_train, 10)

# Kiểm tra kích thước từng tập
for i, part in enumerate(splits):
    print(f"Fold {i+1}: shape = {part.shape}")


Fold 1: shape = (11, 4)
Fold 2: shape = (11, 4)
Fold 3: shape = (11, 4)
Fold 4: shape = (11, 4)
Fold 5: shape = (11, 4)
Fold 6: shape = (10, 4)
Fold 7: shape = (10, 4)
Fold 8: shape = (10, 4)
Fold 9: shape = (10, 4)
Fold 10: shape = (10, 4)
