# DEEP LEARNING
## Pytorch Basic

In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

## Dataset with pytorch

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [8]:
df.shape

(150, 6)

In [11]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)
#Chia dữ liệu với test size = 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1)
y_test = torch.LongTensor(y_test).reshape(-1)

In [12]:
len(y_train)

120

In [13]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
import torch

In [15]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [16]:
#Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [17]:
y.grad_fn

In [18]:
#Thực hiện lan truyền ngược và tính toán các gradient
y.backward()

In [ ]:
#8x^3 + 3x^2 + 6x + 5
x.grad

tensor(93.)

# BTVN 1:
#Cho y = 5x^5 + 6x^3 - 3x + 1. Cho biết độ dốc của đa thức trên ở điểm nào? 

In [2]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = 5*x**5 + 6*x**3 - 3*x + 1
y.backward()

print("Giá trị y:", y.item())
print("Độ dốc tại x = 2:", x.grad.item())


Giá trị y: 203.0
Độ dốc tại x = 2: 469.0


# BTVN 2:
Tạo một tensor ban đầu có giá trị là 2
Định nghĩa hàm số và tính gradient
y = x^3 2x^2 + 5x + 1
hãy tính dy/dx tại giá trị của x
Dùng phương pháp Gradient Descent với Learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

In [ ]:
import torch

# Khởi tạo tensor
x = torch.tensor(2.0, requires_grad=True)

alpha = 0.1

for i in range(10):
    # Định nghĩa hàm
    y = x**3 + 2*x**2 + 5*x + 1
    # Tính gradient
    y.backward()
    print(f"Vòng {i+1}: x = {x.item():.6f}, dy/dx = {x.grad.item():.6f}")
    # Cập nhật x theo Gradient Descent
    with torch.no_grad():
        x -= alpha * x.grad
    # Reset gradient
    x.grad.zero_()


Vòng 1: x = 2.000000, dy/dx = 25.000000
Vòng 2: x = -0.500000, dy/dx = 3.750000
Vòng 3: x = -0.875000, dy/dx = 3.796875
Vòng 4: x = -1.254688, dy/dx = 4.703972
Vòng 5: x = -1.725085, dy/dx = 7.027413
Vòng 6: x = -2.427826, dy/dx = 12.971715
Vòng 7: x = -3.724998, dy/dx = 31.726830
Vòng 8: x = -6.897680, dy/dx = 120.143257
Vòng 9: x = -18.912006, dy/dx = 1002.343933
Vòng 10: x = -119.146408, dy/dx = 42116.011719


# BTVN 3:
Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức y = 3x + 5 + noise
Với noise là một giá trị ngẫu nhiên nhỏ
1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình

In [7]:
import torch

# Tạo dữ liệu giả lập
torch.manual_seed(0)
N = 50
x = torch.rand(N, 1) * 9 + 1      # [1, 10]
noise = torch.randn(N, 1) * 0.5
y = 3 * x + 5 + noise

# 1. Khởi tạo tham số w và b
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

alpha = 0.01

for epoch in range(100):
    y_pred = w * x + b
    # 2. Tính MSE
    mse = torch.mean((y_pred - y) ** 2)
    # 3. Tính Gradient
    mse.backward()
    # 4. Cập nhật tham số
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    # Reset gradient
    w.grad.zero_()
    b.grad.zero_()
    # 5. Theo dõi hội tụ
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}: MSE={mse.item():.4f}, w={w.item():.4f}, b={b.item():.4f}")


Epoch  10: MSE=3.8913, w=3.7183, b=0.5902
Epoch  20: MSE=3.6232, w=3.6927, b=0.7514
Epoch  30: MSE=3.3751, w=3.6680, b=0.9065
Epoch  40: MSE=3.1456, w=3.6443, b=1.0557
Epoch  50: MSE=2.9331, w=3.6214, b=1.1992
Epoch  60: MSE=2.7366, w=3.5995, b=1.3373
Epoch  70: MSE=2.5547, w=3.5783, b=1.4701
Epoch  80: MSE=2.3864, w=3.5580, b=1.5978
Epoch  90: MSE=2.2306, w=3.5384, b=1.7207
Epoch 100: MSE=2.0865, w=3.5196, b=1.8389


In [22]:
import torch
import numpy as np

In [21]:
torch.__version__

'2.7.1+cpu'

In [30]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [27]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [28]:
print(x.dtype)

torch.int64


In [32]:
print(x.type())

torch.LongTensor


In [33]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [34]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [38]:
#Copy and sharing
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [45]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [51]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [52]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN 4: Giải thích 2 trường hợp ở trên

arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)
arr[0] = 99
print(x)
Kết quả:
tensor([0, 1, 2, 3, 4])
tensor([99, 1, 2, 3, 4])
Lí do: torch.from_numpy(arr) chia sẻ chung vùng nhớ với arr
Khi arr thay đổi -> x thay đổi theo
Không tạo bản sao dữ liệu

Còn ở trường hợp 2:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)
arr[0] = 99
print(x)
Kết quả:
tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])
Lí do:
torch.tensor(arr) copy dữ liệu sang vùng nhớ mới
Thay đổi arr không ảnh hưởng đến x

# BTVN 5:
Bạn giúp thầy tạo tensor với 
empyty
zeros
ones
random
Reshape với view và view as

In [4]:
import torch
x = torch.empty(3, 4)
print("empty:", x)
x = torch.zeros(2, 3)
print("zeros:", x)
x = torch.ones(2, 3)
print("ones:", x)
x = torch.rand(2, 3)      
print("random:", x)
x = torch.arange(12)
y = x.view(3, 4)
print("view:", y)
a = torch.zeros(2, 3)
b = torch.arange(6)
c = b.view_as(a)
print("view as:", c)


empty: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
random: tensor([[0.1452, 0.8610, 0.8928],
        [0.0825, 0.1377, 0.6278]])
view: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
view as: tensor([[0, 1, 2],
        [3, 4, 5]])
